services:
  db:
    image: postgres:15
    container_name: online_shop_db_container
    restart: always
    environment:
      POSTGRES_DB: online_shop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  generator:
    build: .
    container_name: data_generator_container
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: online_shop
      DB_USER: admin
      DB_PASS: "12345"
    restart: on-failure

  redis:
    image: redis:7-alpine
    restart: always

  redash-server:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 1
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379"
      REDASH_DATABASE_URL: "postgresql://admin:12345@db/online_shop"
      REDASH_COOKIE_SECRET: "very-secret-key"

  redash-scheduler:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - redash-server
    environment:
      REDASH_REDIS_URL: "redis://redis:6379"
      REDASH_DATABASE_URL: "postgresql://admin:12345@db/online_shop"
      REDASH_COOKIE_SECRET: "very-secret-key"
    command: scheduler

  redash-worker:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - redash-server
    environment:
      REDASH_REDIS_URL: "redis://redis:6379"
      REDASH_DATABASE_URL: "postgresql://admin:12345@db/online_shop"
      REDASH_COOKIE_SECRET: "very-secret-key"
    command: worker

volumes:
  postgres_data: