version: '3.8'

services:
  # Наша база данных
  db:
    image: postgres:15
    container_name: online_shop_db_container
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  generator:
    build: .
    container_name: data_generator_container
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    restart: on-failure

volumes:
  postgres_data: